### ISSUE TITLE
rdfizer: interruzione anomala della procedura di trasformazione dei dati estratti via oai

### ISSUE THREAD

**Issue by oibaf** [ICCD-MiBACT/ArCo#105]
**Indicare quali parti del progetto sono coinvolte nel bug: ontologia, knowledge graph, rdfizer**

rdfizer

**Descrivere il problema**

la trasformazione in rdf dei dati xml estratti via oai registra una eccezione nei casi elencati di seguito (la traccia si riferisce a ICCD11690895)

ERROR 2020-08-10 00:57:22,086 [main] (ErrorHandlerFactory.java:84) - [line: 331, col: 164] {E202} Expecting XML start or end element(s). String data "Brindis" not allowed. Maybe a striping error.
org.apache.jena.riot.RiotException: [line: 331, col: 164] {E202} Expecting XML start or end element(s). String data "Brindis" not allowed. Maybe a striping error.
	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:128)
	at org.apache.jena.riot.lang.LangRDFXML$ErrorHandlerBridge.error(LangRDFXML.java:232)
	at org.apache.jena.rdfxml.xmlinput.impl.ARPSaxErrorHandler.error(ARPSaxErrorHandler.java:37)
	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.warning(XMLHandler.java:196)
	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.warning(XMLHandler.java:173)
	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.warning(XMLHandler.java:168)
	at org.apache.jena.rdfxml.xmlinput.impl.ParserSupport.warning(ParserSupport.java:207)
	at org.apache.jena.rdfxml.xmlinput.states.Frame.warning(Frame.java:55)
	at org.apache.jena.rdfxml.xmlinput.states.Frame.characters(Frame.java:164)
	at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.characters(XMLHandler.java:137)
	at org.apache.xerces.parsers.AbstractSAXParser.characters(Unknown Source)
	at org.apache.xerces.impl.XMLNamespaceBinder.characters(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanContent(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.DTDConfiguration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.jena.rdfxml.xmlinput.impl.RDFXMLParser.parse(RDFXMLParser.java:150)
	at org.apache.jena.rdfxml.xmlinput.ARP.load(ARP.java:118)
	at org.apache.jena.riot.lang.LangRDFXML.parse(LangRDFXML.java:134)
	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:179)
	at org.apache.jena.riot.RDFDataMgr.process(RDFDataMgr.java:859)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:259)
	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:245)
	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:69)
	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:305)
	at it.cnr.istc.stlab.arco.Converter.convert(Converter.java:273)

**Descrivere come riprodurre il problema**

trasformazione dei dati xml estratti via oai dei seguenti identificativi

ICCD13625078
ICCD13673275
ICCD13673251
ICCD13673215
ICCD13670747
ICCD13666863
ICCD13666327
ICCD13670720
ICCD13670713
ICCD13667776
ICCD13667742
ICCD13666871
ICCD13626218
ICCD13673173
ICCD13626211
ICCD13673221
ICCD13673131
ICCD13673116
ICCD13670705
ICCD13667751
ICCD13666885
ICCD13666852
ICCD13626224
ICCD13673152
ICCD13670692
ICCD13670729
ICCD13625049
ICCD13673186
ICCD12019184
ICCD13626208
ICCD11238495
ICCD11165719
ICCD11167619
ICCD11167613
ICCD11165767
ICCD11165733
ICCD11165765
ICCD11690895
ICCD11690364
ICCD11167587
ICCD11167583
ICCD11167579
ICCD11167576
ICCD11166312
ICCD11165771
ICCD11166314
ICCD11165780
ICCD11166310
ICCD11165777
ICCD11168028
ICCD11168025
ICCD11168020
ICCD11168016
ICCD11168011
ICCD11168006
ICCD11167663
ICCD11167637
ICCD11167632
ICCD11167629
ICCD11167624
ICCD11167601
ICCD11167599
ICCD11167592
ICCD13673101
ICCD13670795
ICCD11692480

**Comportamento atteso**

la procedura di trasformazione va a buon fine

**Informazioni aggiuntive**

**Comment by margherita-porena** [comment]
The issue has been solved with commit 870f710
